// Code generated by "stringer -type=ErrType"; DO NOT EDIT.

package demux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ETUnknown-0]
	_ = x[ETChanExists-1]
	_ = x[ETChanNotFound-2]
	_ = x[ETMiddleware-3]
	_ = x[ETChanTimeout-4]
}

const _ErrType_name = "ETUnknownETChanExistsETChanNotFoundETMiddlewareETChanTimeout"

var _ErrType_index = [...]uint8{0, 9, 21, 35, 47, 60}

func (i ErrType) String() string {
	if i >= ErrType(len(_ErrType_index)-1) {
		return "ErrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrType_name[_ErrType_index[i]:_ErrType_index[i+1]]
}
