// Code generated by "stringer -type=MutexType"; DO NOT EDIT.

package demux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoMutex-0]
	_ = x[Mutex-1]
	_ = x[RWMutex-2]
}

const _MutexType_name = "NoMutexMutexRWMutex"

var _MutexType_index = [...]uint8{0, 7, 12, 19}

func (i MutexType) String() string {
	if i >= MutexType(len(_MutexType_index)-1) {
		return "MutexType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MutexType_name[_MutexType_index[i]:_MutexType_index[i+1]]
}
